### ISSUE TITLE
Ripple effect "undefined is not a function (evaluating '_this._onLayoutChange(evt.nativeEvent.layout)')"

### ISSUE THREAD

**Issue by BrnoPCmaniak** [xinthink/react-native-material-kit#163]
![photo416392398289086877](https://cloud.githubusercontent.com/assets/1249759/15447890/a6a0f2a0-1f50-11e6-914c-78a4363c7e2b.jpg)

```javascript
import React from 'react-native';
import {
  MKTextField,
  MKColor,
  MKButton,
  mdl,
} from 'react-native-material-kit';

const FlatButton = MKButton.flatButton()
  .withText('BUTTON')
  .build();

return (
      <View style={styles.container}>
        <FlatButton/>
        <View style={styles.header}>
          ...
      </View>
    );
```

Pretty much the same happens to TextField and probably any other rnmk component.

**Comment by mmelitzer** [comment]
I had the same issue, although I can't say 100% sure why it's caused it seems to be a transpiler issue.
The methods that cause this are all arrow functions:
`someMethod = () => { ....}`

In case you have a babelrc file add the react-native-stage-0 preset, e.g.:
`
{
  "sourceMaps": "inline",
  "presets": [
    "react-native-stage-0"
  ],
  "passPerPreset": true
}
`

Check out the descriptions on the Github page in regard to clean up the cache though!

**Comment by siderakis** [comment]
I've been getting a lot of these errors recently (after upgrading RN to 26).

I think arrow functions aren't working properly in RN. After binding this manually this issue and a bunch other errors were fixed.

I've tried `react-native-stage-0` with no success.

**Comment by Crash--** [comment]
@BrnoPCmaniak @siderakis Seems there is a solution in the SO post. Can you confirm the fix?

**Comment by IcanDivideBy0** [comment]
Adding the following in `.babelrc` fix it

```json
{
  "plugins": [
    "transform-class-properties"
  ]
}
```
This should definitly be in the README.md, lost way too many time in babel output for this. Strange thing is that `react-native` preset seems to include it, so I don't know why i have to add it a second time...

Babel 6.11.4
RN 0.31.0
