### ISSUE TITLE
Doesn't work with RN 0.12

### ISSUE THREAD

**Issue by kinhunt** [xinthink/react-native-material-kit#32]
Red screen with this error:

Expected dynamic type `int64`, but had type `string`

**Comment by JonnyBGod** [comment]
Same problem.

<img width="373" alt="screenshot 2015-10-10 15 49 12" src="https://cloud.githubusercontent.com/assets/405206/10411709/835978f2-6f66-11e5-9929-cf7474dca36e.png">

```
Warning: Failed propType: typeChecker is not a function Check the render method of `SigninScreen`.reactConsoleError @ ExceptionsManager.js:87
ExceptionsManager.js:87 JSON value 'rgba(255,255,255,.5)' of type NSString cannot be converted to NSNumberreactConsoleError @ ExceptionsManager.js:87logIfNoNativeHook @ RCTLog.js:36messageHandlers.executeJSCall @ debuggerWorker.js:25onmessage @ debuggerWorker.js:42
```

```
JSON value 'rgba(255,255,255,.5)' of type NSString cannot be converted to NSNumberreactConsoleError @ ExceptionsManager.js:87logIfNoNativeHook @ RCTLog.js:36messageHandlers.executeJSCall @ debuggerWorker.js:25onmessage @ debuggerWorker.js:42
WarningBox.js:61 devtools socket closed
```

**Comment by xinthink** [comment]
fixed in v0.2.0
